*"*"use source
*"*"Local Interface:
*"**********************************************************************
" STOB viewer - handles structured objects (STOB)
" STOB objects are auto-generated by CDS views (DDLS)
" Uses DDDDLSRC02BT table to find corresponding DDLS and delegates to DDLS viewer
CLASS zcl_abgagt_viewer_stob DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_abgagt_viewer.
ENDCLASS.

CLASS zcl_abgagt_viewer_stob IMPLEMENTATION.
  METHOD zif_abgagt_viewer~get_info.
    " STOB objects are auto-generated by CDS views (DDLS)
    " Use DDDDLSRC02BT table to find the corresponding DDLS name
    " Then delegate to DDLS viewer to get the source

    DATA: lv_ddls_name TYPE ddlname,
          lv_devclass TYPE tadir-devclass,
          lv_obj_name TYPE tadir-obj_name,
          lo_viewer TYPE REF TO zif_abgagt_viewer,
          lo_factory TYPE REF TO zcl_abgagt_viewer_factory,
          ls_ddls_info TYPE zcl_abgagt_command_view=>ty_view_object.

    rs_info-name = iv_name.
    rs_info-type = 'STOB'.
    rs_info-type_text = 'Structured Object'.

    " Uppercase the object name for queries
    lv_obj_name = iv_name.
    TRANSLATE lv_obj_name TO UPPER CASE.

    " Get package from TADIR (STOB type)
    SELECT SINGLE devclass FROM tadir
      INTO lv_devclass
      WHERE obj_name = lv_obj_name
        AND object = 'STOB'.

    IF sy-subrc = 0.
      rs_info-devclass = lv_devclass.
    ENDIF.

    " Find corresponding DDLS name from DDDDLSRC02BT
    " STRUCOBJN = STOB name, DDLNAME = corresponding DDLS source
    SELECT SINGLE ddlname FROM ddddlsrc02bt
      INTO lv_ddls_name
      WHERE strucobjn = lv_obj_name
        AND as4local = 'A'.

    IF sy-subrc <> 0.
      " Try inactive version
      SELECT SINGLE ddlname FROM ddddlsrc02bt
        INTO lv_ddls_name
        WHERE strucobjn = lv_obj_name
          AND as4local = 'M'.
    ENDIF.

    IF lv_ddls_name IS NOT INITIAL.
      " Found DDLS - delegate to DDLS viewer
      TRY.
          lo_factory = zcl_abgagt_viewer_factory=>get_instance( ).
          lo_viewer = lo_factory->get_viewer( 'DDLS' ).
          " Convert DDLNAME to string for viewer interface
          ls_ddls_info = lo_viewer->get_info( CONV string( lv_ddls_name ) ).

          " Copy relevant info from DDLS viewer
          rs_info-source = ls_ddls_info-source.
          rs_info-type_text = |Structured Object (from CDS View { lv_ddls_name })|.

          IF lv_devclass IS NOT INITIAL.
            rs_info-description = |Structured Object { iv_name } in { lv_devclass } (CDS View: { lv_ddls_name })|.
          ELSE.
            rs_info-description = |Structured Object { iv_name } (CDS View: { lv_ddls_name })|.
          ENDIF.

          " Check if DDLS viewer marked it as not found
          IF ls_ddls_info-not_found = abap_true.
            rs_info-not_found = abap_true.
          ENDIF.

        CATCH cx_root.
          " Error getting DDLS viewer or reading info
          IF lv_devclass IS NOT INITIAL.
            rs_info-description = |Structured Object { iv_name } in { lv_devclass } (DDLS: { lv_ddls_name })|.
          ELSE.
            rs_info-description = |Structured Object { iv_name } (DDLS: { lv_ddls_name })|.
          ENDIF.
          rs_info-source = |* Error reading CDS view source for { lv_ddls_name }|.
      ENDTRY.

    ELSE.
      " No DDLS found for this STOB
      IF lv_devclass IS NOT INITIAL.
        " Found in TADIR but couldn't find corresponding DDLS
        rs_info-description = |Structured Object { iv_name } in { lv_devclass } (no DDLS mapping found)|.
        rs_info-source = '* No corresponding CDS view (DDLS) found for this STOB object'.
      ELSE.
        " Not found in TADIR at all
        rs_info-description = |Object { iv_name } not found in TADIR|.
        rs_info-not_found = abap_true.
      ENDIF.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
