/**
 * ABAP HTTP request wrapper with CSRF token management
 */
const https = require('https');
const http = require('http');
const pathModule = require('path');
const fs = require('fs');

const COOKIE_FILE = '.abapgit_agent_cookies.txt';

/**
 * Read cookies from Netscape format file
 * @returns {string} Cookie header string
 */
function readNetscapeCookies() {
  const cookiePath = pathModule.join(process.cwd(), COOKIE_FILE);
  if (!fs.existsSync(cookiePath)) return '';

  const content = fs.readFileSync(cookiePath, 'utf8').trim();
  if (!content) return '';

  // Check if it's Netscape format (has tabs)
  if (content.includes('\t')) {
    const lines = content.split('\n');
    const cookies = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || (trimmed.startsWith('#') && !trimmed.startsWith('#HttpOnly'))) continue;

      const parts = trimmed.split('\t');
      if (parts.length >= 7) {
        cookies.push(`${parts[5]}=${parts[6]}`);
      }
    }

    return cookies.join('; ');
  }

  // Simple format - just return as-is
  return content;
}

/**
 * Save cookies to Netscape format cookie file
 * @param {string} cookies - Cookie string from Set-Cookie header
 * @param {string} host - Host name
 */
function saveCookies(cookies, host) {
  const cookiePath = pathModule.join(process.cwd(), COOKIE_FILE);

  // Parse cookies and convert to Netscape format
  const cookieList = cookies.split(';').map(c => c.trim()).filter(Boolean);
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies.html',
    '# This file was generated by libcurl! Edit at your own risk.'
  ];

  for (const cookie of cookieList) {
    const [name, ...valueParts] = cookie.split('=');
    const value = valueParts.join('=');

    // HttpOnly cookies get #HttpOnly_ prefix
    const domain = name.includes('SAP') || name.includes('MYSAP') || name.includes('SAPLOGON')
      ? `#HttpOnly_${host}`
      : host;

    // Format: domain, flag, path, secure, expiration, name, value
    lines.push(`${domain}\tFALSE\t/\tFALSE\t0\t${name.trim()}\t${value}`);
  }

  fs.writeFileSync(cookiePath, lines.join('\n'));
}

/**
 * ABAP HTTP client with CSRF token management
 */
class AbapHttp {
  constructor(config) {
    this.config = config;
    this.csrfToken = null;
  }

  /**
   * Fetch CSRF token using GET /health with X-CSRF-Token: fetch
   * @returns {Promise<string>} CSRF token
   */
  async fetchCsrfToken() {
    const url = new URL(`/sap/bc/z_abapgit_agent/health`, `https://${this.config.host}:${this.config.sapport}`);

    return new Promise((resolve, reject) => {
      // Clear stale cookies before fetching new token
      const cookiePath = pathModule.join(process.cwd(), COOKIE_FILE);
      if (fs.existsSync(cookiePath)) {
        fs.unlinkSync(cookiePath);
      }

      const cookieHeader = readNetscapeCookies();

      const options = {
        hostname: url.hostname,
        port: url.port,
        path: url.pathname,
        method: 'GET',
        headers: {
          'Authorization': `Basic ${Buffer.from(`${this.config.user}:${this.config.password}`).toString('base64')}`,
          'sap-client': this.config.client,
          'sap-language': this.config.language || 'EN',
          'X-CSRF-Token': 'fetch',
          'Content-Type': 'application/json',
          ...(cookieHeader && { 'Cookie': cookieHeader })
        },
        agent: new https.Agent({ rejectUnauthorized: false })
      };

      const req = https.request(options, (res) => {
        const csrfToken = res.headers['x-csrf-token'];

        // Save new cookies from response
        const setCookie = res.headers['set-cookie'];
        if (setCookie) {
          const cookies = Array.isArray(setCookie)
            ? setCookie.map(c => c.split(';')[0]).join('; ')
            : setCookie.split(';')[0];
          saveCookies(cookies, this.config.host);
        }

        let body = '';
        res.on('data', chunk => body += chunk);
        res.on('end', () => {
          this.csrfToken = csrfToken;
          resolve(csrfToken);
        });
      });

      req.on('error', reject);
      req.end();
    });
  }

  /**
   * Make HTTP request to ABAP REST endpoint
   * @param {string} method - HTTP method (GET, POST, DELETE)
   * @param {string} urlPath - URL path
   * @param {object} data - Request body (for POST)
   * @param {object} options - Additional options (headers, csrfToken)
   * @returns {Promise<object>} Response JSON
   */
  async request(method, urlPath, data = null, options = {}) {
    return new Promise((resolve, reject) => {
      const url = new URL(urlPath, `https://${this.config.host}:${this.config.sapport}`);

      const headers = {
        'Content-Type': 'application/json',
        'sap-client': this.config.client,
        'sap-language': this.config.language || 'EN',
        ...options.headers
      };

      // Add authorization
      headers['Authorization'] = `Basic ${Buffer.from(`${this.config.user}:${this.config.password}`).toString('base64')}`;

      // Add CSRF token for POST
      if (method === 'POST' && options.csrfToken) {
        headers['X-CSRF-Token'] = options.csrfToken;
      }

      // Add cookies if available
      const cookieHeader = readNetscapeCookies();
      if (cookieHeader) {
        headers['Cookie'] = cookieHeader;
      }

      const reqOptions = {
        hostname: url.hostname,
        port: url.port,
        path: url.pathname + url.search,
        method,
        headers,
        agent: new https.Agent({ rejectUnauthorized: false })
      };

      const req = (url.protocol === 'https:' ? https : http).request(reqOptions, (res) => {
        let body = '';
        res.on('data', chunk => body += chunk);
        res.on('end', () => {
          try {
            // Handle unescaped newlines from ABAP - replace actual newlines with \n
            const cleanedBody = body.replace(/\n/g, '\\n');
            resolve(JSON.parse(cleanedBody));
          } catch (e) {
            // Fallback: try to extract JSON from response
            const jsonMatch = body.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
              try {
                resolve(JSON.parse(jsonMatch[0].replace(/\n/g, '\\n')));
              } catch (e2) {
                resolve({ raw: body, error: e2.message });
              }
            } else {
              resolve({ raw: body, error: e.message });
            }
          }
        });
      });

      req.on('error', reject);

      if (data) {
        req.write(JSON.stringify(data));
      }
      req.end();
    });
  }

  /**
   * Convenience method for GET requests
   * @param {string} urlPath - URL path
   * @param {object} options - Additional options
   * @returns {Promise<object>} Response JSON
   */
  async get(urlPath, options = {}) {
    return this.request('GET', urlPath, null, options);
  }

  /**
   * Convenience method for POST requests
   * @param {string} urlPath - URL path
   * @param {object} data - Request body
   * @param {object} options - Additional options (must include csrfToken)
   * @returns {Promise<object>} Response JSON
   */
  async post(urlPath, data, options = {}) {
    return this.request('POST', urlPath, data, options);
  }

  /**
   * Convenience method for DELETE requests
   * @param {string} urlPath - URL path
   * @param {object} options - Additional options
   * @returns {Promise<object>} Response JSON
   */
  async delete(urlPath, options = {}) {
    return this.request('DELETE', urlPath, null, options);
  }
}

module.exports = {
  AbapHttp,
  readNetscapeCookies,
  saveCookies
};
